group=NoiseTool

[file]
filename=${NoiseTool_RESOURCES_DIR}/VertexLight.frag
alias=VertexLight.frag

[file]
filename=${NoiseTool_RESOURCES_DIR}/VertexLight.vert
alias=VertexLight.vert

[file]
filename=${NoiseTool_RESOURCES_DIR}/Heightmap.frag
alias=Heightmap.frag

[file]
filename=${NoiseTool_RESOURCES_DIR}/Heightmap.vert
alias=Heightmap.vert

[file]
filename=${imgui_SOURCE_DIR}/misc/fonts/DroidSans.ttf
alias=Font.ttf

[file]
filename=${NoiseTool_RESOURCES_DIR}/fontawesome.otf
alias=fontawesome.otf
